model_params:
  model: Model


args:
  expdir: "/mnt/HDD/home/druzhinin/kaggle/kaggle_severstal/stage_experiments/resized_1_8"
  logdir: "/mnt/HDD/home/druzhinin/kaggle/kaggle_severstal/logdir/1.1.fpn_dpn131_resized"

distributed_params:
  opt_level: O1

stages:
  state_params:
    main_metric: &reduce_metric dice
    minimize_metric: False

  data_params:
    num_workers: 4

  criterion_params:
    criterion: BCEWithLogitsLoss

  scheduler_params:
    scheduler: ReduceLROnPlateau
    mode: min
    patience: 3
    verbose: True

  callbacks_params:
    loss:
      callback: CriterionCallback
    optimizer:
      callback: OptimizerCallback
    catalyst_dice:
      callback: DiceCallback
      threshold: 0.5
      prefix: catalyst_dice
    catalyst_iou:
      callback: IouCallback
      threshold: 0.5
      prefix: catalyst_iou
    dice:
      callback: MyDice
      threshold: 0.5
    iou:
      callback: MyIOU
      threshold: 0.5
    scheduler:
      callback: SchedulerCallback
      reduce_metric: *reduce_metric
    saver:
      callback: CheckpointCallback

  stage1:
    data_params:
      batch_size: 8

    state_params:
      num_epochs: 10

    optimizer_params:
      optimizer: Adam

      lr_linear_scaling:
        lr: 0.0005
        base_batch_size: 8
      weight_decay: 0.00001

  stage2:
    data_params:
      batch_size: 4

    state_params:
      num_epochs: 15

    optimizer_params:
      optimizer: Adam

      lr_linear_scaling:
        lr: 0.0001
        base_batch_size: 8
      weight_decay: 0.00001

  stage3:
    data_params:
      batch_size: 3

    state_params:
      num_epochs: 20

    optimizer_params:
      optimizer: Adam

      lr_linear_scaling:
        lr: 0.00005
        base_batch_size: 8
      weight_decay: 0.00001

  stage4:
    data_params:
      batch_size: 3

    state_params:
      num_epochs: 5

    optimizer_params:
      optimizer: Adam

      lr_linear_scaling:
        lr: 0.00005
        base_batch_size: 8
      weight_decay: 0.00001